name: Pruebas Git

on:
  push:
    branches: [ "Brda37" ]
  pull_request:
    branches: [ "Brda37" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Set up gradle
        uses: gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew assemble
